/* Generated By:JavaCC: Do not edit this line. TermReaderConstants.java */
package ua.gradsoft.termware.parsers.terms;

public interface TermReaderConstants {

  int EOF = 0;
  int TRUE = 18;
  int FALSE = 19;
  int INTEGER_LITERAL = 20;
  int STRING_LITERAL = 21;
  int DOUBLE_LITERAL = 22;
  int EXPONENT = 23;
  int NIL = 24;
  int IN = 25;
  int IDENT = 26;
  int X_LITERAL = 27;
  int LEFT_ARROW = 28;
  int LOGICAL_OR = 29;
  int LOGICAL_AND = 30;
  int BIT_OR = 31;
  int BIT_AND = 32;
  int EQ = 33;
  int NEQ = 34;
  int LESS = 35;
  int GREATER = 36;
  int LESS_EQ = 37;
  int GREATER_EQ = 38;
  int EQ_GREATER = 39;
  int LEFT_SHIFT = 40;
  int RIGHT_SHIFT = 41;
  int PLUS = 42;
  int MINUS = 43;
  int MULTIPLY = 44;
  int DIVIDE = 45;
  int TWO_DIVIDE = 46;
  int MOD = 47;
  int LOGICAL_NOT = 48;
  int BIT_NEGATE = 49;
  int DOT = 50;
  int TWO_DOTS = 51;
  int COMMA = 52;
  int QUESTION = 53;
  int TWO_TWO_DOTS = 54;
  int ARGS_DOTS = 55;
  int NAMPERSAND = 56;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\";\"",
    "\"let\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"where\"",
    "\"!->\"",
    "\"<-\"",
    "\"{\"",
    "\"}\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<EXPONENT>",
    "\"NIL\"",
    "\"in\"",
    "<IDENT>",
    "<X_LITERAL>",
    "\"->\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=>\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"//\"",
    "\"%\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\":\"",
    "\",\"",
    "\"?\"",
    "\"::\"",
    "\"..\"",
    "\"#@\"",
  };

}
